"""backend/server.py

Generated by LSH
Updated: 2025-09-07
Desc: Bootstrap FastAPI server. Initialize databases, CORS, logging and router loading.
"""

import importlib
import os
import pkgutil

try:
    from . import router as router  # when imported as package
except Exception:  # pragma: no cover
    import router  # when running from backend/ working dir

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from starlette.middleware.sessions import SessionMiddleware

# Support both package import (backend.server) and module import (server)
try:  # package context
    from .lib.Auth import AuthConfig  # type: ignore
    from .lib.Database import (  # type: ignore
        DatabaseManager,
        loadQueries,
        sqlObserver,
        startWatchingQueryFolder,
        setQueryConfig,
    )
    from .lib import Database as DB  # type: ignore
    from .lib.Logger import logger  # type: ignore
    from .lib.Response import errorResponse  # type: ignore
    from .lib.Middleware import RequestLogMiddleware  # type: ignore
    from .lib.OpenAPI import attachOpenAPI  # type: ignore
    from .lib.Config import get_config  # type: ignore
except Exception:  # module context
    from lib.Auth import AuthConfig
    from lib.Database import (
        DatabaseManager,
        loadQueries,
        sqlObserver,
        startWatchingQueryFolder,
        setQueryConfig,
    )
    from lib import Database as DB
    from lib.Logger import logger
    from lib.Response import errorResponse
    from lib.Middleware import RequestLogMiddleware
    from lib.OpenAPI import attachOpenAPI
    from lib.Config import get_config

app = FastAPI()

# ---------------------------------------------------------------------------
# Config helpers
# ---------------------------------------------------------------------------


async def onShutdown():
    """Cleanup on application shutdown."""
    for manager in DB.dbManagers.values():
        if hasattr(manager, "disconnect"):
            await manager.disconnect()
    if sqlObserver:
        sqlObserver.stop()
        sqlObserver.join()


# ---------------------------------------------------------------------------
# Startup tasks
# ---------------------------------------------------------------------------


async def onStartup():
    """Initialise databases, query loader and auth config."""
    logger.info("database connect start")
    global sqlObserver

    config = get_config()
    dbSections = [s for s in config.sections() if s.startswith("DATABASE")]

    for section in dbSections:
        dbConfig = config[section]
        dbName = dbConfig.get("name", section.lower())
        dbType = dbConfig.get("type")

        # skip if already provided
        if dbName in DB.dbManagers:
            continue

        if dbType == "sqlite":
            # 데이터베이스 파일 경로 안전 처리(None/빈문자열 대비)
            raw_path = dbConfig.get("database")
            base_dir = os.path.dirname(__file__)
            if not raw_path:
                dbPath = os.path.join(base_dir, "data", "main.db")
            else:
                dbPath = raw_path
                if not os.path.isabs(dbPath):
                    dbPath = os.path.join(base_dir, dbPath)
            os.makedirs(os.path.dirname(dbPath), exist_ok=True)
            dbUrl = f"sqlite:///{dbPath}"
        elif dbType in ["mysql", "mariadb"]:
            host = dbConfig.get("host", "localhost")
            port = dbConfig.get("port", "3306")
            database = dbConfig.get("database")
            user = dbConfig.get("user")
            password = dbConfig.get("password")
            # Use async driver for compatibility with `databases` (async I/O)
            dbUrl = f"mysql+aiomysql://{user}:{password}@{host}:{port}/{database}"
        elif dbType == "postgresql":
            host = dbConfig.get("host", "localhost")
            port = dbConfig.get("port", "5432")
            database = dbConfig.get("database")
            user = dbConfig.get("user")
            password = dbConfig.get("password")
            dbUrl = f"postgresql://{user}:{password}@{host}:{port}/{database}"
        else:
            logger.warning(f"unsupported database type: {dbType}")
            continue

        try:
            if dbName not in DB.dbManagers or not getattr(DB.dbManagers[dbName], "databaseUrl", None):
                DB.dbManagers[dbName] = DatabaseManager(dbUrl)
            if hasattr(DB.dbManagers[dbName], "connect"):
                await DB.dbManagers[dbName].connect()
            logger.info(f"database connected: {dbName}")
        except Exception as e:
            logger.error(f"database connect failed ({dbName}): {str(e)}")

    logger.info("database connect done")
    logger.info("query load start")

    # query loader
    try:
        dbGlobal = config["DATABASE"]
    except Exception:
        dbGlobal = None

    base_dir = os.path.dirname(__file__)
    repo_root = os.path.dirname(base_dir)
    qdir_raw = (dbGlobal.get("query_dir") if dbGlobal else None) or "query"
    if not os.path.isabs(qdir_raw):
        norm = qdir_raw.replace("\\", "/")
        if norm.startswith("backend/"):
            qdir_abs = os.path.join(repo_root, qdir_raw)
        else:
            qdir_abs = os.path.join(base_dir, qdir_raw)
    else:
        qdir_abs = qdir_raw

    qwatch = True
    try:
        qwatch = dbGlobal.getboolean("query_watch", True) if dbGlobal else True
    except Exception:
        pass

    try:
        qdebounce = dbGlobal.getint("query_watch_debounce_ms", 150) if dbGlobal else 150
    except Exception:
        qdebounce = 150

    setQueryConfig(qdir_abs, qwatch, qdebounce)

    loadQueries()
    logger.info("query load done")
    sqlObserver = startWatchingQueryFolder()
    if sqlObserver:
        logger.info("query watcher started")

    # load auth config
    config = get_config()
    authConfig = config["AUTH"]
    AuthConfig.initConfig(
        secretKey=authConfig["secret_key"],
        expireMinutes=authConfig.getint("token_expire", 3600) // 60,
        tokenEnable=authConfig.getboolean("token_enable", True),
    )

    # Note: User table creation/seeding is handled by scripts/tests or AuthService.
    # Avoid implicit DDL/DML on startup to respect external DBs.

    try:
        attachOpenAPI(app, get_config())
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Application setup
# ---------------------------------------------------------------------------

# Ensure configuration is loaded once (singleton), then access via get_config()
# expose primary DB name to DB helper for non-hardcoded access
# Primary DB 이름 노출(초기화 실패 시 조용히 무시)
try:
    DB.setPrimaryDbName(get_config()["DATABASE"].get("name", "main_db"))
except Exception:
    pass

# CORS config
origins_raw = get_config("config.ini")["CORS"].get("allow_origins", "").strip()
origin_regex_raw = get_config()["CORS"].get("allow_origin_regex", "").strip()

# If '*' is specified while credentials are enabled, fall back to a single dev origin.
if origins_raw == "*":
    origins = [os.getenv("DEV_WEB_ORIGIN", "http://localhost:3000")]
else:
    origins = [o.strip() for o in origins_raw.split(",") if o.strip()]

allow_origin_regex = origin_regex_raw or None

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_origin_regex=allow_origin_regex,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"]
)

# register event handlers
app.add_event_handler("startup", onStartup)
app.add_event_handler("shutdown", onShutdown)

# request logging + request id propagation
app.add_middleware(RequestLogMiddleware)

# Session (cookie-based) for Web
app.add_middleware(
    SessionMiddleware,
    secret_key=get_config()["AUTH"]["secret_key"],
    session_cookie=get_config()["AUTH"].get("session_cookie", "sid"),
    same_site="lax",
    https_only=os.getenv("ENV", "dev").lower() == "prod",
    max_age=get_config()["AUTH"].getint("token_expire", 3600),
)

# load routers
logger.info("router load start")
# Optional: disable demo/example routers via config
disable_demo_routes = False
try:
    disable_demo_routes = get_config()["SERVER"].getboolean("disable_demo_routes", False)
except Exception:
    disable_demo_routes = False

for _, moduleName, _ in pkgutil.iter_modules(router.__path__, router.__name__ + "."):
    # Skip demo TransactionRouter when disabled
    if disable_demo_routes and moduleName.endswith(".TransactionRouter"):
        continue
    module = importlib.import_module(moduleName)
    if hasattr(module, "router"):
        app.include_router(module.router)
logger.info("router load done")


@app.exception_handler(Exception)
async def globalExceptionHandler(request: Request, exc: Exception):
    return JSONResponse(
        status_code=500,
        content=errorResponse(message=str(exc), result={"path": request.url.path}),
    )
