-- PostgreSQL source migration for BE-AUTH-002.
-- Apply explicitly during deployment; request handlers must not run DDL.
-- name: migration.authVersion
ALTER TABLE T_USER
    ADD COLUMN IF NOT EXISTS AUTH_VERSION BIGINT NOT NULL DEFAULT 0;

-- name: migration.passwordResetToken
CREATE TABLE IF NOT EXISTS T_PASSWORD_RESET_TOKEN (
    TOKEN_HASH CHAR(64) PRIMARY KEY,
    USER_ID TEXT NOT NULL REFERENCES T_USER(USER_ID) ON DELETE CASCADE,
    CREATED_AT_MS BIGINT NOT NULL,
    EXPIRES_AT_MS BIGINT NOT NULL,
    USED_AT_MS BIGINT
);

-- name: migration.passwordResetLatestToken
CREATE UNIQUE INDEX IF NOT EXISTS UX_PASSWORD_RESET_ACTIVE_USER
    ON T_PASSWORD_RESET_TOKEN (USER_ID)
    WHERE USED_AT_MS IS NULL;

-- name: migration.passwordResetExpiry
CREATE INDEX IF NOT EXISTS IX_PASSWORD_RESET_EXPIRES
    ON T_PASSWORD_RESET_TOKEN (EXPIRES_AT_MS);
