/**
 * 파일명: layout.jsx
 * 작성자: LSH
 * 갱신일: 2025-09-13
 * 설명: 앱 전역 레이아웃
 */
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppShell from "./AppShell";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppShell>
          <div className="bg-gray-50 text-gray-950 min-h-screen">{children}</div>
        </AppShell>
      </body>
    </html>
  );
}
